export type ContainerState = 'created' | 'running' | 'stopped' | 'error';
export type HealthStatus = 'healthy' | 'unhealthy' | 'unknown';

export interface ContainerVolume {
	name: string;        // logical name e.g. "data"
	mountPath: string;   // path inside container e.g. "/app/data"
	sizeMb?: number;     // hint, Docker doesn't enforce on local driver
}

export interface ContainerVolumeRow extends ContainerVolume {
	id: string;                  // UUID
	containerId: string;
	dockerVolumeName: string;    // mcp-vol-{shortId}-{name}
	createdAt: number;
}

export interface ContainerResources {
	memoryMb: number;
	cpus: number;
	tmpSizeMb: number;
}

export interface HealthCheck {
	status: HealthStatus;
	failCount: number;
	restartCount: number;
	lastCheck: number | null; // unix ms
}

/** Self-restart policy read from the container's own `privos.health.*` labels. */
export interface HealthPolicy {
	path: string;       // HTTP path to probe, e.g. "/health"
	maxFails: number;   // consecutive failures before a restart is triggered
	restart: boolean;   // whether the monitor is allowed to auto-restart this container
}

export interface Container {
	id: string; // UUID generated by cluster
	appId: string | null; // FK to privos-chat mcp_apps._id
	workspaceId: string | null;
	listingId: string | null;
	versionDigest: string | null;
	dockerContainerId: string;
	dockerContainerName: string;
	image: string;
	tag: string;
	state: ContainerState;
	internalUrl: string;
	port: number;
	hostPort: number | null;
	resources: ContainerResources;
	envVars: Record<string, string>;
	healthCheck: HealthCheck;
	createdAt: number;
	startedAt: number | null;
	stoppedAt: number | null;
	volumes: ContainerVolume[]; // computed from volumes table
	adopted?: boolean;  // true if imported via adopt (vs deployed)
	subdomain?: string | null; // DNS label routed to this container via Caddy
	domain?: string | null;    // base domain the subdomain is published under
	healthPolicy?: HealthPolicy; // self-restart policy read from labels (in-memory health monitor)
}

export interface Setting<T = unknown> {
	key: string;
	value: T;
	updatedAt: number;
	updatedBy: string | null;
}

export interface ClusterResources {
	host: {
		totalMemoryMb: number;
		cpuCount: number;
	};
	allocated: {
		memoryMb: number;
		cpus: number;
		containers: number;
	};
	available: {
		memoryMb: number;
		cpus: number;
	};
}

export interface DeployRequest {
	workspaceId?: string;
	listingId?: string;
	versionDigest?: string;
	image: string;
	tag?: string;
	digest?: string;
	port?: number;
	resources?: Partial<ContainerResources>;
	envVars?: Record<string, string>;
	appId?: string;
	volumes?: ContainerVolume[];
	subdomain?: string | null;
	domain?: string | null;
}

export interface RedeployRequest {
	workspaceId?: string;
	versionDigest?: string;
	image?: string;
	tag?: string;
	digest?: string;
	resources?: Partial<ContainerResources>;
	rolling?: boolean; // default true — use rolling (zero-downtime) redeploy when safe
	subdomain?: string | null;
	domain?: string | null;
}

export interface ContainerStatus {
	state: ContainerState;
	cpuPercent: number;
	memoryUsageMb: number;
	memoryLimitMb: number;
	memoryPercent: number;
	uptime: number | null;
	restarts: number;
	healthStatus: HealthStatus;
}
