import type { JsonWebKey } from 'node:crypto';

export type ContainerState = 'created' | 'running' | 'stopped' | 'error';
export type HealthStatus = 'healthy' | 'unhealthy' | 'unknown';

export interface ContainerVolume {
	name: string;        // logical name e.g. "data"
	mountPath: string;   // path inside container e.g. "/app/data"
	sizeMb?: number;     // hint, Docker doesn't enforce on local driver
}

export interface ContainerVolumeRow extends ContainerVolume {
	id: string;                  // UUID
	containerId: string;
	dockerVolumeName: string;    // mcp-vol-{shortId}-{name}
	createdAt: number;
}

export interface ContainerResources {
	memoryMb: number;
	cpus: number;
	tmpSizeMb: number;
}

export interface HealthCheck {
	status: HealthStatus;
	failCount: number;
	restartCount: number;
	lastCheck: number | null; // unix ms
}

/** Self-restart policy read from the container's own `privos.health.*` labels. */
export interface HealthPolicy {
	path: string;       // HTTP path to probe, e.g. "/health"
	maxFails: number;   // consecutive failures before a restart is triggered
	restart: boolean;   // whether the monitor is allowed to auto-restart this container
}

export interface Container {
	id: string; // UUID generated by cluster
	appId: string | null; // FK to privos-chat mcp_apps._id
	workspaceId: string | null;
	listingId: string | null;
	versionDigest: string | null;
	dockerContainerId: string;
	dockerContainerName: string;
	image: string;
	tag: string;
	imageDigest: string | null;
	state: ContainerState;
	internalUrl: string;
	port: number;
	hostPort: number | null;
	resources: ContainerResources;
	envVars: Record<string, string>;
	healthCheck: HealthCheck;
	createdAt: number;
	startedAt: number | null;
	stoppedAt: number | null;
	volumes: ContainerVolume[]; // computed from volumes table
	adopted?: boolean;  // true if imported via adopt (vs deployed)
	subdomain?: string | null; // DNS label routed to this container via Caddy
	domain?: string | null;    // base domain the subdomain is published under
	healthPolicy?: HealthPolicy; // self-restart policy read from labels (in-memory health monitor)
	mcpV2?: boolean; // compatibility proxy bit: MCP workloads expose UI only; private paths stay blocked
	mcpV3?: boolean; // v3 workloads reconcile only through the signed generation-aware path
	/** Epoch ms the container was last observed OOM-killed (Docker inspect's
	 * `State.OOMKilled` + `State.FinishedAt`), captured by the in-memory health
	 * monitor before any restart. Null when never observed OOM-killed since the
	 * agent process started. */
	oomKilledAt?: number | null;
}

export interface Setting<T = unknown> {
	key: string;
	value: T;
	updatedAt: number;
	updatedBy: string | null;
}

export interface ClusterResources {
	host: {
		totalMemoryMb: number;
		cpuCount: number;
	};
	allocated: {
		memoryMb: number;
		cpus: number;
		containers: number;
	};
	available: {
		memoryMb: number;
		cpus: number;
	};
}

export interface DeployRequest {
	workspaceId?: string;
	listingId?: string;
	versionDigest?: string;
	image: string;
	tag?: string;
	digest?: string;
	port?: number;
	resources?: Partial<ContainerResources>;
	envVars?: Record<string, string>;
	/**
	 * Platform-owned PRIVOS_* variables the master injects. Kept apart from
	 * `envVars` because the operator-supplied map is refused the PRIVOS_
	 * namespace; merging happens at container create, where platform wins.
	 */
	platformEnvVars?: Record<string, string>;
	/** Names within `envVars` whose values must never reach a Docker label. */
	secretEnvKeys?: string[];
	appId?: string;
	volumes?: ContainerVolume[];
	subdomain?: string | null;
	domain?: string | null;
	mcpBinding?: McpRuntimeBinding;
	mcpV3Binding?: McpRuntimeBindingV3;
}

export interface McpRuntimeBinding {
	clusterId: string;
	nodeId: string;
	workspaceId: string;
	installationId: string;
	mcpAppId: string;
	replicaId: string;
	imageDigest: string;
	manifestDigest: string;
	receiptHash: string;
	grantEpoch: number;
	deploymentGrantHash: string;
	hubOrigin: string;
	hubKid: string;
	hubPublicJwk: JsonWebKey;
}

/** Additive v3 generation-affine runtime binding. */
export interface McpRuntimeBindingV3 {
	protocolVersion: 3;
	clusterId: string;
	nodeId: string;
	workspaceId: string;
	deploymentId: string;
	generationId: string;
	generationNumber: number;
	runtimeInstallationId: string;
	mcpAppId: string;
	replicaId: string;
	containerId: string;
	imageDigest: string;
	manifestDigest: string;
	approvalReceiptHash: string;
	authorizationEpoch: number;
	deploymentGrantHash: string;
	resourceManifestHash: string;
	runtimeResourceInventoryHash?: string;
	hubOrigin: string;
	hubKid: string;
	hubPublicJwk: JsonWebKey;
}

export interface RedeployRequest {
	workspaceId?: string;
	versionDigest?: string;
	image?: string;
	tag?: string;
	digest?: string;
	resources?: Partial<ContainerResources>;
	rolling?: boolean; // default true — use rolling (zero-downtime) redeploy when safe
	subdomain?: string | null;
	domain?: string | null;
	/**
	 * Present only for a signed managed-runtime (v3) upgrade swap. Its presence
	 * is what tells the raw-redeploy secret guard this call is upgrade-aware
	 * (rebuilds the container with the full env + labels + broker binding the
	 * master already holds for this generation) rather than the naive path the
	 * guard exists to block. `imageDigest` here is the NEW target digest; every
	 * other binding field is restated unchanged (D1 — an upgrade rotates only
	 * the image, never permissions, resources, or env).
	 */
	mcpV3Binding?: Omit<McpRuntimeBindingV3, 'hubOrigin' | 'hubKid' | 'hubPublicJwk'>;
	/** Required alongside `mcpV3Binding` — restated unchanged, needed to re-finalize the broker binding. */
	runtimeResourceInventoryHash?: string;
	/** Full operator environment (the master's decrypted copy), required alongside `mcpV3Binding`. */
	envVars?: Record<string, string>;
	platformEnvVars?: Record<string, string>;
	secretEnvKeys?: string[];
}

export interface ContainerStatus {
	state: ContainerState;
	cpuPercent: number;
	memoryUsageMb: number;
	memoryLimitMb: number;
	memoryPercent: number;
	uptime: number | null;
	restarts: number;
	healthStatus: HealthStatus;
}
